name: Docker Build and Push

on:
  push:
    branches:
      - main  # O la rama que prefieras

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.FFabianna }}
          password: ${{ secrets.FFabianna }}

      - name: Construir y enviar la imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: fabiianna/react-imagen:latest  
